# Generated by Django 5.1.5 on 2025-02-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_session_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
    ]
