# Generated by Django 5.1.5 on 2025-02-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming_session_tracker', '0005_remove_payment_grooming_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='balance_due',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
