# Generated by Django 5.1.5 on 2025-01-22 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='groomer_profiles/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groomer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
