# Generated by Django 5.1.5 on 2025-02-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
