# Generated by Django 5.1.5 on 2025-02-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0005_appointment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pet_type',
            field=models.CharField(default='Cat', help_text='E.g., Dog, Cat, Rabbit, Bird', max_length=100),
            preserve_default=False,
        ),
    ]
