# Generated by Django 5.1.5 on 2025-02-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0007_feedback_feedbackresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='groomer',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='FeedbackResponse',
        ),
    ]
