# Generated by Django 5.1.5 on 2025-02-06 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0009_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Experience years cannot be less than 0.')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Price cannot be less than 0.')]),
        ),
    ]
