# Generated by Django 5.1.5 on 2025-03-05 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0010_alter_groomerprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Experience years cannot be less than 0.')]),
        ),
    ]
