# Generated by Django 5.1.5 on 2025-03-05 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0011_alter_groomerprofile_experience_years'),
        ('pet_owner', '0009_petbreed_pettype_remove_petownerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pet_owner.petbreed'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pet_owner.pettype'),
        ),
    ]
