# Generated by Django 5.1.5 on 2025-03-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0012_service_breed_alter_service_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='breed',
        ),
    ]
