# Generated by Django 5.1.5 on 2025-03-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0013_remove_service_breed'),
        ('pet_owner', '0009_petbreed_pettype_remove_petownerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet_owner.pet'),
        ),
    ]
