# Generated by Django 5.1.5 on 2025-02-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(default='Dog', help_text='E.g., Dog, Cat, Rabbit, Bird', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
