# Generated by Django 5.1.5 on 2025-02-03 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0009_response'),
        ('pet_owner', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default='No comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groom_interface.service'),
        ),
    ]
