# Generated by Django 5.1.5 on 2025-02-04 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groom_interface', '0009_response'),
        ('pet_owner', '0006_alter_feedback_comment_alter_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='groom_interface.service'),
        ),
    ]
