# Generated by Django 5.1.5 on 2025-02-06 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owner', '0007_alter_feedback_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Weight cannot be less than 0.')]),
        ),
    ]
