# Generated by Django 5.1.5 on 2025-03-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
